DROP TABLE IF EXISTS Admin ;
DROP TABLE IF EXISTS  Employee;
DROP TABLE IF EXISTS Department ;

CREATE TABLE IF NOT EXISTS Admin(
    id INTEGER PRIMARY KEY ,
    email VARCHAR NOT NULL UNIQUE, 
    password VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Department(
    id INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE Employee(
    id INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR  NOT NULL,
    email VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL UNIQUE,
    salary INTEGER NOT NULL,
    dept_id INTEGER NOT NULL,
    FOREIGN KEY (dept_id) REFERENCES Department(id) 
);
